version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=20205780'
      - 'POSTGRES_DB=example_service'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8081:8080
